//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth3.Shared.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth3.Shared.Languages.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string AboutWindowCloseButton {
            get {
                return ResourceManager.GetString("AboutWindowCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string AllCategoryDisplayName {
            get {
                return ResourceManager.GetString("AllCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c) 2025 rkttu.com, All rights reserved..
        /// </summary>
        public static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is released as open source under the Affero GPL v3 license..
        /// </summary>
        public static string AppLicense {
            get {
                return ResourceManager.GetString("AppLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure • Clean • Always.
        /// </summary>
        public static string AppSlogan {
            get {
                return ResourceManager.GetString("AppSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCloth.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 식탁보® (TableCloth) trademark is protected by trademark law in the Republic of Korea..
        /// </summary>
        public static string AppTrademark {
            get {
                return ResourceManager.GetString("AppTrademark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking.
        /// </summary>
        public static string BankingCategoryDisplayName {
            get {
                return ResourceManager.GetString("BankingCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check _Update.
        /// </summary>
        public static string CheckUpdateButton {
            get {
                return ResourceManager.GetString("CheckUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Cards.
        /// </summary>
        public static string CreditCardCategoryDisplayName {
            get {
                return ResourceManager.GetString("CreditCardCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string EducationCategoryDisplayName {
            get {
                return ResourceManager.GetString("EducationCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financing.
        /// </summary>
        public static string FinancingCategoryDisplayName {
            get {
                return ResourceManager.GetString("FinancingCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/yourtablecloth/TableCloth.
        /// </summary>
        public static string GitHubUrl {
            get {
                return ResourceManager.GetString("GitHubUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government.
        /// </summary>
        public static string GovernmentCategoryDisplayName {
            get {
                return ResourceManager.GetString("GovernmentCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        public static string InsuranceCategoryDisplayName {
            get {
                return ResourceManager.GetString("InsuranceCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Update Available.
        /// </summary>
        public static string NewUpdateAvailable {
            get {
                return ResourceManager.GetString("NewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Updates Available.
        /// </summary>
        public static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string OtherCategoryDisplayName {
            get {
                return ResourceManager.GetString("OtherCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://yourtablecloth.app.
        /// </summary>
        public static string ProjectWebSiteUrl {
            get {
                return ResourceManager.GetString("ProjectWebSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securities.
        /// </summary>
        public static string SecurityCategoryDisplayName {
            get {
                return ResourceManager.GetString("SecurityCategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (untagged build).
        /// </summary>
        public static string UntaggedBuild {
            get {
                return ResourceManager.GetString("UntaggedBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version ({0}) is available. Would you like to open the download page?.
        /// </summary>
        public static string UpdateAvailableMessage {
            get {
                return ResourceManager.GetString("UpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for updates. Please try again later..
        /// </summary>
        public static string UpdateCheckFailedMessage {
            get {
                return ResourceManager.GetString("UpdateCheckFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using the latest version..
        /// </summary>
        public static string UpToDateMessage {
            get {
                return ResourceManager.GetString("UpToDateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit _GitHub.
        /// </summary>
        public static string VisitGitHubButton {
            get {
                return ResourceManager.GetString("VisitGitHubButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit _Web Site.
        /// </summary>
        public static string VisitWebSiteButton {
            get {
                return ResourceManager.GetString("VisitWebSiteButton", resourceCulture);
            }
        }
    }
}
