//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableCloth3.Launcher.Languages {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LauncherStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LauncherStrings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableCloth3.Launcher.Languages.LauncherStrings", typeof(LauncherStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _About...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Add Folders...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string AddFoldersButton {
            get {
                return ResourceManager.GetString("AddFoldersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C_lear All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ClearAllFoldersButton {
            get {
                return ResourceManager.GetString("ClearAllFoldersButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close _Anyway과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CloseAnywayButton {
            get {
                return ResourceManager.GetString("CloseAnywayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CloseApp {
            get {
                return ResourceManager.GetString("CloseApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Close과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CloseManageWindow {
            get {
                return ResourceManager.GetString("CloseManageWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Claude Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyClaudeSettings {
            get {
                return ResourceManager.GetString("CopyClaudeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy MCP settings for Claude Desktop to clipboard과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyClaudeSettingsTooltip {
            get {
                return ResourceManager.GetString("CopyClaudeSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy settings for use in Claude Desktop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CopyClaudeDesktopConfig {
            get {
                return ResourceManager.GetString("CopyClaudeDesktopConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder Access과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FolderAccess {
            get {
                return ResourceManager.GetString("FolderAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the folder you want to use within the sandbox.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FolderManageWindowInstruction {
            get {
                return ResourceManager.GetString("FolderManageWindowInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage Folders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string FolderManageWindowTitle {
            get {
                return ResourceManager.GetString("FolderManageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hardware Access과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string HardwareAccess {
            get {
                return ResourceManager.GetString("HardwareAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TableCloth과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LauncherMainWindowTitle {
            get {
                return ResourceManager.GetString("LauncherMainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Launch과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LaunchSandbox {
            get {
                return ResourceManager.GetString("LaunchSandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manage F_olders...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ManageFolders {
            get {
                return ResourceManager.GetString("ManageFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MCP Server Connection Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string McpServerConnectionStatus {
            get {
                return ResourceManager.GetString("McpServerConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MCP server connected successfully!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string McpServerConnectedSuccessfully {
            get {
                return ResourceManager.GetString("McpServerConnectedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MCP server is currently running and may be used by Claude Desktop.
        ///
        ///Do you want to minimize the application to keep the server running, or do you want to close the application completely?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string McpServerCloseConfirmationMessage {
            get {
                return ResourceManager.GetString("McpServerCloseConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MCP Server Running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string McpServerCloseConfirmationTitle {
            get {
                return ResourceManager.GetString("McpServerCloseConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Minimize과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MinimizeButton {
            get {
                return ResourceManager.GetString("MinimizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mount _NPKI Folders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MountNpkiFolders {
            get {
                return ResourceManager.GetString("MountNpkiFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mount Specific _Folders과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MountSpecificFolders {
            get {
                return ResourceManager.GetString("MountSpecificFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RefreshButton {
            get {
                return ResourceManager.GetString("RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Refresh MCP server status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RefreshMcpServerStatusTooltip {
            get {
                return ResourceManager.GetString("RefreshMcpServerStatusTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RemoveFolderButton {
            get {
                return ResourceManager.GetString("RemoveFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sandbox Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SandboxSettings {
            get {
                return ResourceManager.GetString("SandboxSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Share _Printers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SharePrinters {
            get {
                return ResourceManager.GetString("SharePrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use _Microphone과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UseMicrophone {
            get {
                return ResourceManager.GetString("UseMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use _Web Camera과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UseWebCamera {
            get {
                return ResourceManager.GetString("UseWebCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
